#端口
server:
  port: 881
  tomcat:
    uri-encoding: UTF-8
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
    - image/png
    - image/jpeg
    - image/jpg
    - text/html
    - application/javascript
    - text/css
    - application/octet-stream
    - application/json

logging:
  level:
    com.luolight.SeaweedS.mappers: debug

#Eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      waitTimeInMsWhenSyncEmpty: 0
  server:
    enableSelfPreservation: false
    

#spring的阿里数据源-118.31.120.123
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seaweedSister?useUnicode=true&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall
    maxActive: 650
    initialSize: 50
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    removeAbandoned: true
    removeAbandonedTimeout: 180000
    logAbandoned: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
