package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.LuolightWebsite;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LuolightWebsiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_website
     *
     * @mbggenerated
     */
    @Delete({
        "delete from luolight_website",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_website
     *
     * @mbggenerated
     */
    @Insert({
        "insert into luolight_website (id, website_name, ",
        "website_value)",
        "values (#{id,jdbcType=INTEGER}, #{websiteName,jdbcType=VARCHAR}, ",
        "#{websiteValue,jdbcType=VARCHAR})"
    })
    int insert(LuolightWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_website
     *
     * @mbggenerated
     */
    @InsertProvider(type=LuolightWebsiteSqlProvider.class, method="insertSelective")
    int insertSelective(LuolightWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_website
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, website_name, website_value",
        "from luolight_website",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="website_name", property="websiteName", jdbcType=JdbcType.VARCHAR),
        @Result(column="website_value", property="websiteValue", jdbcType=JdbcType.VARCHAR)
    })
    LuolightWebsite selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_website
     *
     * @mbggenerated
     */
    @UpdateProvider(type=LuolightWebsiteSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LuolightWebsite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_website
     *
     * @mbggenerated
     */
    @Update({
        "update luolight_website",
        "set website_name = #{websiteName,jdbcType=VARCHAR},",
          "website_value = #{websiteValue,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LuolightWebsite record);
}