package com.luolight.SeaweedS.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.luolight.SeaweedS.models.LuolightAboutme;

public class LuolightAboutmeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_aboutme
     *
     * @mbggenerated
     */
    public String insertSelective(LuolightAboutme record) {
        BEGIN();
        INSERT_INTO("luolight_aboutme");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getMsgCon() != null) {
            VALUES("msg_con", "#{msgCon,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgTime() != null) {
            VALUES("msg_time", "#{msgTime,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgSort() != null) {
            VALUES("msg_sort", "#{msgSort,jdbcType=INTEGER}");
        }
        
        if (record.getMsgPhotos() != null) {
            VALUES("msg_photos", "#{msgPhotos,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_aboutme
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(LuolightAboutme record) {
        BEGIN();
        UPDATE("luolight_aboutme");
        
        if (record.getMsgCon() != null) {
            SET("msg_con = #{msgCon,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgTime() != null) {
            SET("msg_time = #{msgTime,jdbcType=VARCHAR}");
        }
        
        if (record.getMsgSort() != null) {
            SET("msg_sort = #{msgSort,jdbcType=INTEGER}");
        }
        
        if (record.getMsgPhotos() != null) {
            SET("msg_photos = #{msgPhotos,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}