package com.luolight.SeaweedS.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.luolight.SeaweedS.models.LuolightShowimg;

public class LuolightShowimgSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_showimg
     *
     * @mbggenerated
     */
    public String insertSelective(LuolightShowimg record) {
        BEGIN();
        INSERT_INTO("luolight_showimg");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getImageUrl() != null) {
            VALUES("image_url", "#{imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getDesc() != null) {
            VALUES("desc", "#{desc,jdbcType=VARCHAR}");
        }
        
        if (record.getLinked() != null) {
            VALUES("linked", "#{linked,jdbcType=VARCHAR}");
        }
        
        if (record.getMore() != null) {
            VALUES("more", "#{more,jdbcType=VARCHAR}");
        }
        
        if (record.getFrompage() != null) {
            VALUES("frompage", "#{frompage,jdbcType=VARCHAR}");
        }
        
        if (record.getPosition() != null) {
            VALUES("position", "#{position,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_showimg
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(LuolightShowimg record) {
        BEGIN();
        UPDATE("luolight_showimg");
        
        if (record.getImageUrl() != null) {
            SET("image_url = #{imageUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getDesc() != null) {
            SET("desc = #{desc,jdbcType=VARCHAR}");
        }
        
        if (record.getLinked() != null) {
            SET("linked = #{linked,jdbcType=VARCHAR}");
        }
        
        if (record.getMore() != null) {
            SET("more = #{more,jdbcType=VARCHAR}");
        }
        
        if (record.getFrompage() != null) {
            SET("frompage = #{frompage,jdbcType=VARCHAR}");
        }
        
        if (record.getPosition() != null) {
            SET("position = #{position,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}