package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.LuolightMenus;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LuolightMenusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_menus
     *
     * @mbggenerated
     */
    @Delete({
        "delete from luolight_menus",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_menus
     *
     * @mbggenerated
     */
    @Insert({
        "insert into luolight_menus (id, name, ",
        "url)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{url,jdbcType=VARCHAR})"
    })
    int insert(LuolightMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_menus
     *
     * @mbggenerated
     */
    @InsertProvider(type=LuolightMenusSqlProvider.class, method="insertSelective")
    int insertSelective(LuolightMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_menus
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, name, url",
        "from luolight_menus",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR)
    })
    LuolightMenus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_menus
     *
     * @mbggenerated
     */
    @UpdateProvider(type=LuolightMenusSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LuolightMenus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_menus
     *
     * @mbggenerated
     */
    @Update({
        "update luolight_menus",
        "set name = #{name,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LuolightMenus record);
}