package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.LuolightAboutme;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LuolightAboutmeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_aboutme
     *
     * @mbggenerated
     */
    @Delete({
        "delete from luolight_aboutme",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_aboutme
     *
     * @mbggenerated
     */
    @Insert({
        "insert into luolight_aboutme (id, msg_con, ",
        "msg_time, msg_sort, ",
        "msg_photos)",
        "values (#{id,jdbcType=INTEGER}, #{msgCon,jdbcType=VARCHAR}, ",
        "#{msgTime,jdbcType=VARCHAR}, #{msgSort,jdbcType=INTEGER}, ",
        "#{msgPhotos,jdbcType=VARCHAR})"
    })
    int insert(LuolightAboutme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_aboutme
     *
     * @mbggenerated
     */
    @InsertProvider(type=LuolightAboutmeSqlProvider.class, method="insertSelective")
    int insertSelective(LuolightAboutme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_aboutme
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, msg_con, msg_time, msg_sort, msg_photos",
        "from luolight_aboutme",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="msg_con", property="msgCon", jdbcType=JdbcType.VARCHAR),
        @Result(column="msg_time", property="msgTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="msg_sort", property="msgSort", jdbcType=JdbcType.INTEGER),
        @Result(column="msg_photos", property="msgPhotos", jdbcType=JdbcType.VARCHAR)
    })
    LuolightAboutme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_aboutme
     *
     * @mbggenerated
     */
    @UpdateProvider(type=LuolightAboutmeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LuolightAboutme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_aboutme
     *
     * @mbggenerated
     */
    @Update({
        "update luolight_aboutme",
        "set msg_con = #{msgCon,jdbcType=VARCHAR},",
          "msg_time = #{msgTime,jdbcType=VARCHAR},",
          "msg_sort = #{msgSort,jdbcType=INTEGER},",
          "msg_photos = #{msgPhotos,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LuolightAboutme record);
}