package com.luolight.SeaweedS.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.luolight.SeaweedS.models.LuolightApiargs;

public class LuolightApiargsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_apiargs
     *
     * @mbggenerated
     */
    public String insertSelective(LuolightApiargs record) {
        BEGIN();
        INSERT_INTO("luolight_apiargs");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getArgstype() != null) {
            VALUES("argstype", "#{argstype,jdbcType=INTEGER}");
        }
        
        if (record.getArgssimple() != null) {
            VALUES("argssimple", "#{argssimple,jdbcType=VARCHAR}");
        }
        
        if (record.getArgsisneed() != null) {
            VALUES("argsisneed", "#{argsisneed,jdbcType=INTEGER}");
        }
        
        if (record.getArgsdesc() != null) {
            VALUES("argsdesc", "#{argsdesc,jdbcType=VARCHAR}");
        }
        
        if (record.getArgssize() != null) {
            VALUES("argssize", "#{argssize,jdbcType=VARCHAR}");
        }
        
        if (record.getApiid() != null) {
            VALUES("apiid", "#{apiid,jdbcType=INTEGER}");
        }
        
        if (record.getArgsname() != null) {
            VALUES("argsname", "#{argsname,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_apiargs
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(LuolightApiargs record) {
        BEGIN();
        UPDATE("luolight_apiargs");
        
        if (record.getArgstype() != null) {
            SET("argstype = #{argstype,jdbcType=INTEGER}");
        }
        
        if (record.getArgssimple() != null) {
            SET("argssimple = #{argssimple,jdbcType=VARCHAR}");
        }
        
        if (record.getArgsisneed() != null) {
            SET("argsisneed = #{argsisneed,jdbcType=INTEGER}");
        }
        
        if (record.getArgsdesc() != null) {
            SET("argsdesc = #{argsdesc,jdbcType=VARCHAR}");
        }
        
        if (record.getArgssize() != null) {
            SET("argssize = #{argssize,jdbcType=VARCHAR}");
        }
        
        if (record.getApiid() != null) {
            SET("apiid = #{apiid,jdbcType=INTEGER}");
        }
        
        if (record.getArgsname() != null) {
            SET("argsname = #{argsname,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}