package com.luolight.SeaweedS.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.luolight.SeaweedS.models.LuolightWebsite;

public class LuolightWebsiteSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_website
     *
     * @mbggenerated
     */
    public String insertSelective(LuolightWebsite record) {
        BEGIN();
        INSERT_INTO("luolight_website");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getWebsiteName() != null) {
            VALUES("website_name", "#{websiteName,jdbcType=VARCHAR}");
        }
        
        if (record.getWebsiteValue() != null) {
            VALUES("website_value", "#{websiteValue,jdbcType=VARCHAR}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_website
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(LuolightWebsite record) {
        BEGIN();
        UPDATE("luolight_website");
        
        if (record.getWebsiteName() != null) {
            SET("website_name = #{websiteName,jdbcType=VARCHAR}");
        }
        
        if (record.getWebsiteValue() != null) {
            SET("website_value = #{websiteValue,jdbcType=VARCHAR}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}