package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.LuolightApi;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LuolightApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_api
     *
     * @mbggenerated
     */
    @Delete({
        "delete from luolight_api",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_api
     *
     * @mbggenerated
     */
    @Insert({
        "insert into luolight_api (id, apiname, ",
        "apidesc, apiurl, ",
        "apireturnsimple, apitype)",
        "values (#{id,jdbcType=INTEGER}, #{apiname,jdbcType=VARCHAR}, ",
        "#{apidesc,jdbcType=VARCHAR}, #{apiurl,jdbcType=VARCHAR}, ",
        "#{apireturnsimple,jdbcType=VARCHAR}, #{apitype,jdbcType=INTEGER})"
    })
    int insert(LuolightApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_api
     *
     * @mbggenerated
     */
    @InsertProvider(type=LuolightApiSqlProvider.class, method="insertSelective")
    int insertSelective(LuolightApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_api
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, apiname, apidesc, apiurl, apireturnsimple, apitype",
        "from luolight_api",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="apiname", property="apiname", jdbcType=JdbcType.VARCHAR),
        @Result(column="apidesc", property="apidesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="apiurl", property="apiurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="apireturnsimple", property="apireturnsimple", jdbcType=JdbcType.VARCHAR),
        @Result(column="apitype", property="apitype", jdbcType=JdbcType.INTEGER)
    })
    LuolightApi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_api
     *
     * @mbggenerated
     */
    @UpdateProvider(type=LuolightApiSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LuolightApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_api
     *
     * @mbggenerated
     */
    @Update({
        "update luolight_api",
        "set apiname = #{apiname,jdbcType=VARCHAR},",
          "apidesc = #{apidesc,jdbcType=VARCHAR},",
          "apiurl = #{apiurl,jdbcType=VARCHAR},",
          "apireturnsimple = #{apireturnsimple,jdbcType=VARCHAR},",
          "apitype = #{apitype,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LuolightApi record);
}