package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.LuolightApiargs;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LuolightApiargsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_apiargs
     *
     * @mbggenerated
     */
    @Delete({
        "delete from luolight_apiargs",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_apiargs
     *
     * @mbggenerated
     */
    @Insert({
        "insert into luolight_apiargs (id, argstype, ",
        "argssimple, argsisneed, ",
        "argsdesc, argssize, ",
        "apiid, argsname)",
        "values (#{id,jdbcType=INTEGER}, #{argstype,jdbcType=INTEGER}, ",
        "#{argssimple,jdbcType=VARCHAR}, #{argsisneed,jdbcType=INTEGER}, ",
        "#{argsdesc,jdbcType=VARCHAR}, #{argssize,jdbcType=VARCHAR}, ",
        "#{apiid,jdbcType=INTEGER}, #{argsname,jdbcType=VARCHAR})"
    })
    int insert(LuolightApiargs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_apiargs
     *
     * @mbggenerated
     */
    @InsertProvider(type=LuolightApiargsSqlProvider.class, method="insertSelective")
    int insertSelective(LuolightApiargs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_apiargs
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, argstype, argssimple, argsisneed, argsdesc, argssize, apiid, argsname",
        "from luolight_apiargs",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="argstype", property="argstype", jdbcType=JdbcType.INTEGER),
        @Result(column="argssimple", property="argssimple", jdbcType=JdbcType.VARCHAR),
        @Result(column="argsisneed", property="argsisneed", jdbcType=JdbcType.INTEGER),
        @Result(column="argsdesc", property="argsdesc", jdbcType=JdbcType.VARCHAR),
        @Result(column="argssize", property="argssize", jdbcType=JdbcType.VARCHAR),
        @Result(column="apiid", property="apiid", jdbcType=JdbcType.INTEGER),
        @Result(column="argsname", property="argsname", jdbcType=JdbcType.VARCHAR)
    })
    LuolightApiargs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_apiargs
     *
     * @mbggenerated
     */
    @UpdateProvider(type=LuolightApiargsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LuolightApiargs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_apiargs
     *
     * @mbggenerated
     */
    @Update({
        "update luolight_apiargs",
        "set argstype = #{argstype,jdbcType=INTEGER},",
          "argssimple = #{argssimple,jdbcType=VARCHAR},",
          "argsisneed = #{argsisneed,jdbcType=INTEGER},",
          "argsdesc = #{argsdesc,jdbcType=VARCHAR},",
          "argssize = #{argssize,jdbcType=VARCHAR},",
          "apiid = #{apiid,jdbcType=INTEGER},",
          "argsname = #{argsname,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LuolightApiargs record);
}