package com.luolight.SeaweedS.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.luolight.SeaweedS.models.LuolightApi;

public class LuolightApiSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_api
     *
     * @mbggenerated
     */
    public String insertSelective(LuolightApi record) {
        BEGIN();
        INSERT_INTO("luolight_api");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getApiname() != null) {
            VALUES("apiname", "#{apiname,jdbcType=VARCHAR}");
        }
        
        if (record.getApidesc() != null) {
            VALUES("apidesc", "#{apidesc,jdbcType=VARCHAR}");
        }
        
        if (record.getApiurl() != null) {
            VALUES("apiurl", "#{apiurl,jdbcType=VARCHAR}");
        }
        
        if (record.getApireturnsimple() != null) {
            VALUES("apireturnsimple", "#{apireturnsimple,jdbcType=VARCHAR}");
        }
        
        if (record.getApitype() != null) {
            VALUES("apitype", "#{apitype,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_api
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(LuolightApi record) {
        BEGIN();
        UPDATE("luolight_api");
        
        if (record.getApiname() != null) {
            SET("apiname = #{apiname,jdbcType=VARCHAR}");
        }
        
        if (record.getApidesc() != null) {
            SET("apidesc = #{apidesc,jdbcType=VARCHAR}");
        }
        
        if (record.getApiurl() != null) {
            SET("apiurl = #{apiurl,jdbcType=VARCHAR}");
        }
        
        if (record.getApireturnsimple() != null) {
            SET("apireturnsimple = #{apireturnsimple,jdbcType=VARCHAR}");
        }
        
        if (record.getApitype() != null) {
            SET("apitype = #{apitype,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}