package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.LuolightRecord;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface LuolightRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_record
     *
     * @mbggenerated
     */
    @Delete({
        "delete from luolight_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_record
     *
     * @mbggenerated
     */
    @Insert({
        "insert into luolight_record (id, title, ",
        "time, mainpic, desc, ",
        "likenum, viewnum)",
        "values (#{id,jdbcType=INTEGER}, #{title,jdbcType=VARCHAR}, ",
        "#{time,jdbcType=VARCHAR}, #{mainpic,jdbcType=VARCHAR}, #{desc,jdbcType=VARCHAR}, ",
        "#{likenum,jdbcType=INTEGER}, #{viewnum,jdbcType=INTEGER})"
    })
    int insert(LuolightRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_record
     *
     * @mbggenerated
     */
    @InsertProvider(type=LuolightRecordSqlProvider.class, method="insertSelective")
    int insertSelective(LuolightRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_record
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, title, time, mainpic, desc, likenum, viewnum",
        "from luolight_record",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.VARCHAR),
        @Result(column="mainpic", property="mainpic", jdbcType=JdbcType.VARCHAR),
        @Result(column="desc", property="desc", jdbcType=JdbcType.VARCHAR),
        @Result(column="likenum", property="likenum", jdbcType=JdbcType.INTEGER),
        @Result(column="viewnum", property="viewnum", jdbcType=JdbcType.INTEGER)
    })
    LuolightRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_record
     *
     * @mbggenerated
     */
    @UpdateProvider(type=LuolightRecordSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(LuolightRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_record
     *
     * @mbggenerated
     */
    @Update({
        "update luolight_record",
        "set title = #{title,jdbcType=VARCHAR},",
          "time = #{time,jdbcType=VARCHAR},",
          "mainpic = #{mainpic,jdbcType=VARCHAR},",
          "desc = #{desc,jdbcType=VARCHAR},",
          "likenum = #{likenum,jdbcType=INTEGER},",
          "viewnum = #{viewnum,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(LuolightRecord record);
}