package com.luolight.SeaweedS.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.luolight.SeaweedS.models.LuolightRecord;

public class LuolightRecordSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_record
     *
     * @mbggenerated
     */
    public String insertSelective(LuolightRecord record) {
        BEGIN();
        INSERT_INTO("luolight_record");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getTitle() != null) {
            VALUES("title", "#{title,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=VARCHAR}");
        }
        
        if (record.getMainpic() != null) {
            VALUES("mainpic", "#{mainpic,jdbcType=VARCHAR}");
        }
        
        if (record.getDesc() != null) {
            VALUES("desc", "#{desc,jdbcType=VARCHAR}");
        }
        
        if (record.getLikenum() != null) {
            VALUES("likenum", "#{likenum,jdbcType=INTEGER}");
        }
        
        if (record.getViewnum() != null) {
            VALUES("viewnum", "#{viewnum,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luolight_record
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(LuolightRecord record) {
        BEGIN();
        UPDATE("luolight_record");
        
        if (record.getTitle() != null) {
            SET("title = #{title,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=VARCHAR}");
        }
        
        if (record.getMainpic() != null) {
            SET("mainpic = #{mainpic,jdbcType=VARCHAR}");
        }
        
        if (record.getDesc() != null) {
            SET("desc = #{desc,jdbcType=VARCHAR}");
        }
        
        if (record.getLikenum() != null) {
            SET("likenum = #{likenum,jdbcType=INTEGER}");
        }
        
        if (record.getViewnum() != null) {
            SET("viewnum = #{viewnum,jdbcType=INTEGER}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}