package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.SsModuleWo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SsModuleWoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_wo
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ss_module_wo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_wo
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ss_module_wo (id, module_id, ",
        "user_id, type, description, ",
        "pic, time, operation_level, ",
        "status)",
        "values (#{id,jdbcType=INTEGER}, #{moduleId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{type,jdbcType=SMALLINT}, #{description,jdbcType=VARCHAR}, ",
        "#{pic,jdbcType=VARCHAR}, #{time,jdbcType=TIMESTAMP}, #{operationLevel,jdbcType=SMALLINT}, ",
        "#{status,jdbcType=SMALLINT})"
    })
    int insert(SsModuleWo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_wo
     *
     * @mbggenerated
     */
    @InsertProvider(type=SsModuleWoSqlProvider.class, method="insertSelective")
    int insertSelective(SsModuleWo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_wo
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, module_id, user_id, type, description, pic, time, operation_level, status",
        "from ss_module_wo",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="module_id", property="moduleId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.SMALLINT),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="pic", property="pic", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="operation_level", property="operationLevel", jdbcType=JdbcType.SMALLINT),
        @Result(column="status", property="status", jdbcType=JdbcType.SMALLINT)
    })
    SsModuleWo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_wo
     *
     * @mbggenerated
     */
    @UpdateProvider(type=SsModuleWoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SsModuleWo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_wo
     *
     * @mbggenerated
     */
    @Update({
        "update ss_module_wo",
        "set module_id = #{moduleId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "type = #{type,jdbcType=SMALLINT},",
          "description = #{description,jdbcType=VARCHAR},",
          "pic = #{pic,jdbcType=VARCHAR},",
          "time = #{time,jdbcType=TIMESTAMP},",
          "operation_level = #{operationLevel,jdbcType=SMALLINT},",
          "status = #{status,jdbcType=SMALLINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SsModuleWo record);
}