package com.luolight.SeaweedS.mappers;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.luolight.SeaweedS.models.SsModuleGood;

public class SsModuleGoodSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_good
     *
     * @mbggenerated
     */
    public String insertSelective(SsModuleGood record) {
        BEGIN();
        INSERT_INTO("ss_module_good");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getModuleArticleId() != null) {
            VALUES("module_article_id", "#{moduleArticleId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getHeaderPic() != null) {
            VALUES("header_pic", "#{headerPic,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            VALUES("time", "#{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsRead() != null) {
            VALUES("is_read", "#{isRead,jdbcType=SMALLINT}");
        }
        
        if (record.getIsDelete() != null) {
            VALUES("is_delete", "#{isDelete,jdbcType=SMALLINT}");
        }
        
        if (record.getOperationTime() != null) {
            VALUES("operation_time", "#{operationTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getType() != null) {
            VALUES("type", "#{type,jdbcType=SMALLINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_good
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(SsModuleGood record) {
        BEGIN();
        UPDATE("ss_module_good");
        
        if (record.getModuleArticleId() != null) {
            SET("module_article_id = #{moduleArticleId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getHeaderPic() != null) {
            SET("header_pic = #{headerPic,jdbcType=VARCHAR}");
        }
        
        if (record.getTime() != null) {
            SET("time = #{time,jdbcType=TIMESTAMP}");
        }
        
        if (record.getIsRead() != null) {
            SET("is_read = #{isRead,jdbcType=SMALLINT}");
        }
        
        if (record.getIsDelete() != null) {
            SET("is_delete = #{isDelete,jdbcType=SMALLINT}");
        }
        
        if (record.getOperationTime() != null) {
            SET("operation_time = #{operationTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getType() != null) {
            SET("type = #{type,jdbcType=SMALLINT}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }
}