package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.SsModuleUser;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SsModuleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ss_module_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ss_module_user (id, module_id, ",
        "user_id, time, ",
        "is_delete, delete_time)",
        "values (#{id,jdbcType=INTEGER}, #{moduleId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{time,jdbcType=TIMESTAMP}, ",
        "#{isDelete,jdbcType=SMALLINT}, #{deleteTime,jdbcType=TIMESTAMP})"
    })
    int insert(SsModuleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_user
     *
     * @mbggenerated
     */
    @InsertProvider(type=SsModuleUserSqlProvider.class, method="insertSelective")
    int insertSelective(SsModuleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, module_id, user_id, time, is_delete, delete_time",
        "from ss_module_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="module_id", property="moduleId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_delete", property="isDelete", jdbcType=JdbcType.SMALLINT),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP)
    })
    SsModuleUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_user
     *
     * @mbggenerated
     */
    @UpdateProvider(type=SsModuleUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SsModuleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module_user
     *
     * @mbggenerated
     */
    @Update({
        "update ss_module_user",
        "set module_id = #{moduleId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "time = #{time,jdbcType=TIMESTAMP},",
          "is_delete = #{isDelete,jdbcType=SMALLINT},",
          "delete_time = #{deleteTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SsModuleUser record);
}