package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.SsModule;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SsModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ss_module",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ss_module (id, type_id, ",
        "name, url, url_host, ",
        "is_need, description, ",
        "simple, time, ",
        "level_id, is_delete, ",
        "delete_time, user_id)",
        "values (#{id,jdbcType=INTEGER}, #{typeId,jdbcType=INTEGER}, ",
        "#{name,jdbcType=VARCHAR}, #{url,jdbcType=VARCHAR}, #{urlHost,jdbcType=VARCHAR}, ",
        "#{isNeed,jdbcType=SMALLINT}, #{description,jdbcType=VARCHAR}, ",
        "#{simple,jdbcType=VARCHAR}, #{time,jdbcType=TIMESTAMP}, ",
        "#{levelId,jdbcType=SMALLINT}, #{isDelete,jdbcType=SMALLINT}, ",
        "#{deleteTime,jdbcType=TIMESTAMP}, #{userId,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys = true, keyProperty = "id", keyColumn = "id")
    int insert(SsModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbggenerated
     */
    @InsertProvider(type=SsModuleSqlProvider.class, method="insertSelective")
    int insertSelective(SsModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, type_id, name, url, url_host, is_need, description, simple, time, level_id, ",
        "is_delete, delete_time, user_id",
        "from ss_module",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type_id", property="typeId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="url_host", property="urlHost", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_need", property="isNeed", jdbcType=JdbcType.SMALLINT),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple", property="simple", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="level_id", property="levelId", jdbcType=JdbcType.SMALLINT),
        @Result(column="is_delete", property="isDelete", jdbcType=JdbcType.SMALLINT),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER)
    })
    SsModule selectByPrimaryKey(Integer id);
    
    @Select({
        "select",
        "id, type_id, name, url, url_host, is_need, description, simple, time, level_id, ",
        "is_delete, delete_time, user_id",
        "from ss_module",
        "where url_host = #{urlHost,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type_id", property="typeId", jdbcType=JdbcType.INTEGER),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="url_host", property="urlHost", jdbcType=JdbcType.VARCHAR),
        @Result(column="is_need", property="isNeed", jdbcType=JdbcType.SMALLINT),
        @Result(column="description", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple", property="simple", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="level_id", property="levelId", jdbcType=JdbcType.SMALLINT),
        @Result(column="is_delete", property="isDelete", jdbcType=JdbcType.SMALLINT),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER)
    })
    SsModule selectByUrlHost(String urlHost);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbggenerated
     */
    @UpdateProvider(type=SsModuleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SsModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_module
     *
     * @mbggenerated
     */
    @Update({
        "update ss_module",
        "set type_id = #{typeId,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "url_host = #{urlHost,jdbcType=VARCHAR},",
          "is_need = #{isNeed,jdbcType=SMALLINT},",
          "description = #{description,jdbcType=VARCHAR},",
          "simple = #{simple,jdbcType=VARCHAR},",
          "time = #{time,jdbcType=TIMESTAMP},",
          "level_id = #{levelId,jdbcType=SMALLINT},",
          "is_delete = #{isDelete,jdbcType=SMALLINT},",
          "delete_time = #{deleteTime,jdbcType=TIMESTAMP},",
          "user_id = #{userId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SsModule record);
}