package com.luolight.SeaweedS.mappers;

import com.luolight.SeaweedS.models.SsStructureType;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface SsStructureTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_structure_type
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ss_structure_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_structure_type
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ss_structure_type (id, type_name, ",
        "java_type, user_id, ",
        "is_delete, delete_time)",
        "values (#{id,jdbcType=INTEGER}, #{typeName,jdbcType=VARCHAR}, ",
        "#{javaType,jdbcType=VARCHAR}, #{userId,jdbcType=INTEGER}, ",
        "#{isDelete,jdbcType=SMALLINT}, #{deleteTime,jdbcType=TIMESTAMP})"
    })
    int insert(SsStructureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_structure_type
     *
     * @mbggenerated
     */
    @InsertProvider(type=SsStructureTypeSqlProvider.class, method="insertSelective")
    int insertSelective(SsStructureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_structure_type
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, type_name, java_type, user_id, is_delete, delete_time",
        "from ss_structure_type",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="type_name", property="typeName", jdbcType=JdbcType.VARCHAR),
        @Result(column="java_type", property="javaType", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_delete", property="isDelete", jdbcType=JdbcType.SMALLINT),
        @Result(column="delete_time", property="deleteTime", jdbcType=JdbcType.TIMESTAMP)
    })
    SsStructureType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_structure_type
     *
     * @mbggenerated
     */
    @UpdateProvider(type=SsStructureTypeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(SsStructureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ss_structure_type
     *
     * @mbggenerated
     */
    @Update({
        "update ss_structure_type",
        "set type_name = #{typeName,jdbcType=VARCHAR},",
          "java_type = #{javaType,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "is_delete = #{isDelete,jdbcType=SMALLINT},",
          "delete_time = #{deleteTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(SsStructureType record);
}