package com.luolight.SeaweedS.models;

public class LuolightShowimg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_showimg.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_showimg.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_showimg.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_showimg.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_showimg.linked
     *
     * @mbggenerated
     */
    private String linked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_showimg.more
     *
     * @mbggenerated
     */
    private String more;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_showimg.frompage
     *
     * @mbggenerated
     */
    private String frompage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_showimg.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_showimg.id
     *
     * @return the value of luolight_showimg.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_showimg.id
     *
     * @param id the value for luolight_showimg.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_showimg.image_url
     *
     * @return the value of luolight_showimg.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_showimg.image_url
     *
     * @param imageUrl the value for luolight_showimg.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_showimg.title
     *
     * @return the value of luolight_showimg.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_showimg.title
     *
     * @param title the value for luolight_showimg.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_showimg.desc
     *
     * @return the value of luolight_showimg.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_showimg.desc
     *
     * @param desc the value for luolight_showimg.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_showimg.linked
     *
     * @return the value of luolight_showimg.linked
     *
     * @mbggenerated
     */
    public String getLinked() {
        return linked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_showimg.linked
     *
     * @param linked the value for luolight_showimg.linked
     *
     * @mbggenerated
     */
    public void setLinked(String linked) {
        this.linked = linked == null ? null : linked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_showimg.more
     *
     * @return the value of luolight_showimg.more
     *
     * @mbggenerated
     */
    public String getMore() {
        return more;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_showimg.more
     *
     * @param more the value for luolight_showimg.more
     *
     * @mbggenerated
     */
    public void setMore(String more) {
        this.more = more == null ? null : more.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_showimg.frompage
     *
     * @return the value of luolight_showimg.frompage
     *
     * @mbggenerated
     */
    public String getFrompage() {
        return frompage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_showimg.frompage
     *
     * @param frompage the value for luolight_showimg.frompage
     *
     * @mbggenerated
     */
    public void setFrompage(String frompage) {
        this.frompage = frompage == null ? null : frompage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_showimg.position
     *
     * @return the value of luolight_showimg.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_showimg.position
     *
     * @param position the value for luolight_showimg.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }
}