package com.luolight.SeaweedS.models;

public class LuolightAboutme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_aboutme.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_aboutme.msg_con
     *
     * @mbggenerated
     */
    private String msgCon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_aboutme.msg_time
     *
     * @mbggenerated
     */
    private String msgTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_aboutme.msg_sort
     *
     * @mbggenerated
     */
    private Integer msgSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_aboutme.msg_photos
     *
     * @mbggenerated
     */
    private String msgPhotos;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_aboutme.id
     *
     * @return the value of luolight_aboutme.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_aboutme.id
     *
     * @param id the value for luolight_aboutme.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_aboutme.msg_con
     *
     * @return the value of luolight_aboutme.msg_con
     *
     * @mbggenerated
     */
    public String getMsgCon() {
        return msgCon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_aboutme.msg_con
     *
     * @param msgCon the value for luolight_aboutme.msg_con
     *
     * @mbggenerated
     */
    public void setMsgCon(String msgCon) {
        this.msgCon = msgCon == null ? null : msgCon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_aboutme.msg_time
     *
     * @return the value of luolight_aboutme.msg_time
     *
     * @mbggenerated
     */
    public String getMsgTime() {
        return msgTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_aboutme.msg_time
     *
     * @param msgTime the value for luolight_aboutme.msg_time
     *
     * @mbggenerated
     */
    public void setMsgTime(String msgTime) {
        this.msgTime = msgTime == null ? null : msgTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_aboutme.msg_sort
     *
     * @return the value of luolight_aboutme.msg_sort
     *
     * @mbggenerated
     */
    public Integer getMsgSort() {
        return msgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_aboutme.msg_sort
     *
     * @param msgSort the value for luolight_aboutme.msg_sort
     *
     * @mbggenerated
     */
    public void setMsgSort(Integer msgSort) {
        this.msgSort = msgSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_aboutme.msg_photos
     *
     * @return the value of luolight_aboutme.msg_photos
     *
     * @mbggenerated
     */
    public String getMsgPhotos() {
        return msgPhotos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_aboutme.msg_photos
     *
     * @param msgPhotos the value for luolight_aboutme.msg_photos
     *
     * @mbggenerated
     */
    public void setMsgPhotos(String msgPhotos) {
        this.msgPhotos = msgPhotos == null ? null : msgPhotos.trim();
    }
}