package com.luolight.SeaweedS.models;

public class LuolightApi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_api.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_api.apiname
     *
     * @mbggenerated
     */
    private String apiname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_api.apidesc
     *
     * @mbggenerated
     */
    private String apidesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_api.apiurl
     *
     * @mbggenerated
     */
    private String apiurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_api.apireturnsimple
     *
     * @mbggenerated
     */
    private String apireturnsimple;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_api.apitype
     *
     * @mbggenerated
     */
    private Integer apitype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_api.id
     *
     * @return the value of luolight_api.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_api.id
     *
     * @param id the value for luolight_api.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_api.apiname
     *
     * @return the value of luolight_api.apiname
     *
     * @mbggenerated
     */
    public String getApiname() {
        return apiname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_api.apiname
     *
     * @param apiname the value for luolight_api.apiname
     *
     * @mbggenerated
     */
    public void setApiname(String apiname) {
        this.apiname = apiname == null ? null : apiname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_api.apidesc
     *
     * @return the value of luolight_api.apidesc
     *
     * @mbggenerated
     */
    public String getApidesc() {
        return apidesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_api.apidesc
     *
     * @param apidesc the value for luolight_api.apidesc
     *
     * @mbggenerated
     */
    public void setApidesc(String apidesc) {
        this.apidesc = apidesc == null ? null : apidesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_api.apiurl
     *
     * @return the value of luolight_api.apiurl
     *
     * @mbggenerated
     */
    public String getApiurl() {
        return apiurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_api.apiurl
     *
     * @param apiurl the value for luolight_api.apiurl
     *
     * @mbggenerated
     */
    public void setApiurl(String apiurl) {
        this.apiurl = apiurl == null ? null : apiurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_api.apireturnsimple
     *
     * @return the value of luolight_api.apireturnsimple
     *
     * @mbggenerated
     */
    public String getApireturnsimple() {
        return apireturnsimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_api.apireturnsimple
     *
     * @param apireturnsimple the value for luolight_api.apireturnsimple
     *
     * @mbggenerated
     */
    public void setApireturnsimple(String apireturnsimple) {
        this.apireturnsimple = apireturnsimple == null ? null : apireturnsimple.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_api.apitype
     *
     * @return the value of luolight_api.apitype
     *
     * @mbggenerated
     */
    public Integer getApitype() {
        return apitype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_api.apitype
     *
     * @param apitype the value for luolight_api.apitype
     *
     * @mbggenerated
     */
    public void setApitype(Integer apitype) {
        this.apitype = apitype;
    }
}