package com.luolight.SeaweedS.models;

public class LuolightWebsite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_website.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_website.website_name
     *
     * @mbggenerated
     */
    private String websiteName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_website.website_value
     *
     * @mbggenerated
     */
    private String websiteValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_website.id
     *
     * @return the value of luolight_website.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_website.id
     *
     * @param id the value for luolight_website.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_website.website_name
     *
     * @return the value of luolight_website.website_name
     *
     * @mbggenerated
     */
    public String getWebsiteName() {
        return websiteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_website.website_name
     *
     * @param websiteName the value for luolight_website.website_name
     *
     * @mbggenerated
     */
    public void setWebsiteName(String websiteName) {
        this.websiteName = websiteName == null ? null : websiteName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_website.website_value
     *
     * @return the value of luolight_website.website_value
     *
     * @mbggenerated
     */
    public String getWebsiteValue() {
        return websiteValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_website.website_value
     *
     * @param websiteValue the value for luolight_website.website_value
     *
     * @mbggenerated
     */
    public void setWebsiteValue(String websiteValue) {
        this.websiteValue = websiteValue == null ? null : websiteValue.trim();
    }
}