package com.luolight.SeaweedS.models;

public class LuolightApiargs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_apiargs.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_apiargs.argstype
     *
     * @mbggenerated
     */
    private Integer argstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_apiargs.argssimple
     *
     * @mbggenerated
     */
    private String argssimple;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_apiargs.argsisneed
     *
     * @mbggenerated
     */
    private Integer argsisneed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_apiargs.argsdesc
     *
     * @mbggenerated
     */
    private String argsdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_apiargs.argssize
     *
     * @mbggenerated
     */
    private String argssize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_apiargs.apiid
     *
     * @mbggenerated
     */
    private Integer apiid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_apiargs.argsname
     *
     * @mbggenerated
     */
    private String argsname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_apiargs.id
     *
     * @return the value of luolight_apiargs.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_apiargs.id
     *
     * @param id the value for luolight_apiargs.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_apiargs.argstype
     *
     * @return the value of luolight_apiargs.argstype
     *
     * @mbggenerated
     */
    public Integer getArgstype() {
        return argstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_apiargs.argstype
     *
     * @param argstype the value for luolight_apiargs.argstype
     *
     * @mbggenerated
     */
    public void setArgstype(Integer argstype) {
        this.argstype = argstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_apiargs.argssimple
     *
     * @return the value of luolight_apiargs.argssimple
     *
     * @mbggenerated
     */
    public String getArgssimple() {
        return argssimple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_apiargs.argssimple
     *
     * @param argssimple the value for luolight_apiargs.argssimple
     *
     * @mbggenerated
     */
    public void setArgssimple(String argssimple) {
        this.argssimple = argssimple == null ? null : argssimple.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_apiargs.argsisneed
     *
     * @return the value of luolight_apiargs.argsisneed
     *
     * @mbggenerated
     */
    public Integer getArgsisneed() {
        return argsisneed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_apiargs.argsisneed
     *
     * @param argsisneed the value for luolight_apiargs.argsisneed
     *
     * @mbggenerated
     */
    public void setArgsisneed(Integer argsisneed) {
        this.argsisneed = argsisneed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_apiargs.argsdesc
     *
     * @return the value of luolight_apiargs.argsdesc
     *
     * @mbggenerated
     */
    public String getArgsdesc() {
        return argsdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_apiargs.argsdesc
     *
     * @param argsdesc the value for luolight_apiargs.argsdesc
     *
     * @mbggenerated
     */
    public void setArgsdesc(String argsdesc) {
        this.argsdesc = argsdesc == null ? null : argsdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_apiargs.argssize
     *
     * @return the value of luolight_apiargs.argssize
     *
     * @mbggenerated
     */
    public String getArgssize() {
        return argssize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_apiargs.argssize
     *
     * @param argssize the value for luolight_apiargs.argssize
     *
     * @mbggenerated
     */
    public void setArgssize(String argssize) {
        this.argssize = argssize == null ? null : argssize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_apiargs.apiid
     *
     * @return the value of luolight_apiargs.apiid
     *
     * @mbggenerated
     */
    public Integer getApiid() {
        return apiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_apiargs.apiid
     *
     * @param apiid the value for luolight_apiargs.apiid
     *
     * @mbggenerated
     */
    public void setApiid(Integer apiid) {
        this.apiid = apiid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_apiargs.argsname
     *
     * @return the value of luolight_apiargs.argsname
     *
     * @mbggenerated
     */
    public String getArgsname() {
        return argsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_apiargs.argsname
     *
     * @param argsname the value for luolight_apiargs.argsname
     *
     * @mbggenerated
     */
    public void setArgsname(String argsname) {
        this.argsname = argsname == null ? null : argsname.trim();
    }
}