package com.luolight.SeaweedS.models;

public class LuolightRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_record.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_record.time
     *
     * @mbggenerated
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_record.mainpic
     *
     * @mbggenerated
     */
    private String mainpic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_record.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_record.likenum
     *
     * @mbggenerated
     */
    private Integer likenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column luolight_record.viewnum
     *
     * @mbggenerated
     */
    private Integer viewnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_record.id
     *
     * @return the value of luolight_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_record.id
     *
     * @param id the value for luolight_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_record.title
     *
     * @return the value of luolight_record.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_record.title
     *
     * @param title the value for luolight_record.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_record.time
     *
     * @return the value of luolight_record.time
     *
     * @mbggenerated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_record.time
     *
     * @param time the value for luolight_record.time
     *
     * @mbggenerated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_record.mainpic
     *
     * @return the value of luolight_record.mainpic
     *
     * @mbggenerated
     */
    public String getMainpic() {
        return mainpic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_record.mainpic
     *
     * @param mainpic the value for luolight_record.mainpic
     *
     * @mbggenerated
     */
    public void setMainpic(String mainpic) {
        this.mainpic = mainpic == null ? null : mainpic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_record.desc
     *
     * @return the value of luolight_record.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_record.desc
     *
     * @param desc the value for luolight_record.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_record.likenum
     *
     * @return the value of luolight_record.likenum
     *
     * @mbggenerated
     */
    public Integer getLikenum() {
        return likenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_record.likenum
     *
     * @param likenum the value for luolight_record.likenum
     *
     * @mbggenerated
     */
    public void setLikenum(Integer likenum) {
        this.likenum = likenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column luolight_record.viewnum
     *
     * @return the value of luolight_record.viewnum
     *
     * @mbggenerated
     */
    public Integer getViewnum() {
        return viewnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column luolight_record.viewnum
     *
     * @param viewnum the value for luolight_record.viewnum
     *
     * @mbggenerated
     */
    public void setViewnum(Integer viewnum) {
        this.viewnum = viewnum;
    }
}