package com.luolight.SeaweedS.models;

import java.util.Date;

public class SsModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.url_host
     *
     * @mbggenerated
     */
    private String urlHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.is_need
     *
     * @mbggenerated
     */
    private Short isNeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.simple
     *
     * @mbggenerated
     */
    private String simple;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.level_id
     *
     * @mbggenerated
     */
    private Short levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.id
     *
     * @return the value of ss_module.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.id
     *
     * @param id the value for ss_module.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.type_id
     *
     * @return the value of ss_module.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.type_id
     *
     * @param typeId the value for ss_module.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.name
     *
     * @return the value of ss_module.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.name
     *
     * @param name the value for ss_module.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.url
     *
     * @return the value of ss_module.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.url
     *
     * @param url the value for ss_module.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.url_host
     *
     * @return the value of ss_module.url_host
     *
     * @mbggenerated
     */
    public String getUrlHost() {
        return urlHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.url_host
     *
     * @param urlHost the value for ss_module.url_host
     *
     * @mbggenerated
     */
    public void setUrlHost(String urlHost) {
        this.urlHost = urlHost == null ? null : urlHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.is_need
     *
     * @return the value of ss_module.is_need
     *
     * @mbggenerated
     */
    public Short getIsNeed() {
        return isNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.is_need
     *
     * @param isNeed the value for ss_module.is_need
     *
     * @mbggenerated
     */
    public void setIsNeed(Short isNeed) {
        this.isNeed = isNeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.description
     *
     * @return the value of ss_module.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.description
     *
     * @param description the value for ss_module.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.simple
     *
     * @return the value of ss_module.simple
     *
     * @mbggenerated
     */
    public String getSimple() {
        return simple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.simple
     *
     * @param simple the value for ss_module.simple
     *
     * @mbggenerated
     */
    public void setSimple(String simple) {
        this.simple = simple == null ? null : simple.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.time
     *
     * @return the value of ss_module.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.time
     *
     * @param time the value for ss_module.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.level_id
     *
     * @return the value of ss_module.level_id
     *
     * @mbggenerated
     */
    public Short getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.level_id
     *
     * @param levelId the value for ss_module.level_id
     *
     * @mbggenerated
     */
    public void setLevelId(Short levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.is_delete
     *
     * @return the value of ss_module.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.is_delete
     *
     * @param isDelete the value for ss_module.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.delete_time
     *
     * @return the value of ss_module.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.delete_time
     *
     * @param deleteTime the value for ss_module.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module.user_id
     *
     * @return the value of ss_module.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module.user_id
     *
     * @param userId the value for ss_module.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}