package com.luolight.SeaweedS.models;

import java.util.Date;

public class SsModuleGood {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module_good.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module_good.module_article_id
     *
     * @mbggenerated
     */
    private Integer moduleArticleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module_good.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module_good.header_pic
     *
     * @mbggenerated
     */
    private String headerPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module_good.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module_good.is_read
     *
     * @mbggenerated
     */
    private Short isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module_good.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module_good.operation_time
     *
     * @mbggenerated
     */
    private Date operationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_module_good.type
     *
     * @mbggenerated
     */
    private Short type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module_good.id
     *
     * @return the value of ss_module_good.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module_good.id
     *
     * @param id the value for ss_module_good.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module_good.module_article_id
     *
     * @return the value of ss_module_good.module_article_id
     *
     * @mbggenerated
     */
    public Integer getModuleArticleId() {
        return moduleArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module_good.module_article_id
     *
     * @param moduleArticleId the value for ss_module_good.module_article_id
     *
     * @mbggenerated
     */
    public void setModuleArticleId(Integer moduleArticleId) {
        this.moduleArticleId = moduleArticleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module_good.user_id
     *
     * @return the value of ss_module_good.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module_good.user_id
     *
     * @param userId the value for ss_module_good.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module_good.header_pic
     *
     * @return the value of ss_module_good.header_pic
     *
     * @mbggenerated
     */
    public String getHeaderPic() {
        return headerPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module_good.header_pic
     *
     * @param headerPic the value for ss_module_good.header_pic
     *
     * @mbggenerated
     */
    public void setHeaderPic(String headerPic) {
        this.headerPic = headerPic == null ? null : headerPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module_good.time
     *
     * @return the value of ss_module_good.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module_good.time
     *
     * @param time the value for ss_module_good.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module_good.is_read
     *
     * @return the value of ss_module_good.is_read
     *
     * @mbggenerated
     */
    public Short getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module_good.is_read
     *
     * @param isRead the value for ss_module_good.is_read
     *
     * @mbggenerated
     */
    public void setIsRead(Short isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module_good.is_delete
     *
     * @return the value of ss_module_good.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module_good.is_delete
     *
     * @param isDelete the value for ss_module_good.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module_good.operation_time
     *
     * @return the value of ss_module_good.operation_time
     *
     * @mbggenerated
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module_good.operation_time
     *
     * @param operationTime the value for ss_module_good.operation_time
     *
     * @mbggenerated
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_module_good.type
     *
     * @return the value of ss_module_good.type
     *
     * @mbggenerated
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_module_good.type
     *
     * @param type the value for ss_module_good.type
     *
     * @mbggenerated
     */
    public void setType(Short type) {
        this.type = type;
    }
}