package com.luolight.SeaweedS.models;

import java.util.Date;

public class SsStructureLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_level.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_level.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_level.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_level.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_level.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_level.id
     *
     * @return the value of ss_structure_level.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_level.id
     *
     * @param id the value for ss_structure_level.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_level.content
     *
     * @return the value of ss_structure_level.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_level.content
     *
     * @param content the value for ss_structure_level.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_level.user_id
     *
     * @return the value of ss_structure_level.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_level.user_id
     *
     * @param userId the value for ss_structure_level.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_level.is_delete
     *
     * @return the value of ss_structure_level.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_level.is_delete
     *
     * @param isDelete the value for ss_structure_level.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_level.delete_time
     *
     * @return the value of ss_structure_level.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_level.delete_time
     *
     * @param deleteTime the value for ss_structure_level.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}