package com.luolight.SeaweedS.models;

import java.util.Date;

public class SsStructureType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_type.java_type
     *
     * @mbggenerated
     */
    private String javaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_type.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_type.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_structure_type.delete_time
     *
     * @mbggenerated
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_type.id
     *
     * @return the value of ss_structure_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_type.id
     *
     * @param id the value for ss_structure_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_type.type_name
     *
     * @return the value of ss_structure_type.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_type.type_name
     *
     * @param typeName the value for ss_structure_type.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_type.java_type
     *
     * @return the value of ss_structure_type.java_type
     *
     * @mbggenerated
     */
    public String getJavaType() {
        return javaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_type.java_type
     *
     * @param javaType the value for ss_structure_type.java_type
     *
     * @mbggenerated
     */
    public void setJavaType(String javaType) {
        this.javaType = javaType == null ? null : javaType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_type.user_id
     *
     * @return the value of ss_structure_type.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_type.user_id
     *
     * @param userId the value for ss_structure_type.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_type.is_delete
     *
     * @return the value of ss_structure_type.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_type.is_delete
     *
     * @param isDelete the value for ss_structure_type.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_structure_type.delete_time
     *
     * @return the value of ss_structure_type.delete_time
     *
     * @mbggenerated
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_structure_type.delete_time
     *
     * @param deleteTime the value for ss_structure_type.delete_time
     *
     * @mbggenerated
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}