package com.luolight.SeaweedS.models;

import java.util.Date;

public class SsUrl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_url.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_url.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_url.url_host
     *
     * @mbggenerated
     */
    private String urlHost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_url.is_delete
     *
     * @mbggenerated
     */
    private Short isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ss_url.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_url.id
     *
     * @return the value of ss_url.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_url.id
     *
     * @param id the value for ss_url.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_url.name
     *
     * @return the value of ss_url.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_url.name
     *
     * @param name the value for ss_url.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_url.url_host
     *
     * @return the value of ss_url.url_host
     *
     * @mbggenerated
     */
    public String getUrlHost() {
        return urlHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_url.url_host
     *
     * @param urlHost the value for ss_url.url_host
     *
     * @mbggenerated
     */
    public void setUrlHost(String urlHost) {
        this.urlHost = urlHost == null ? null : urlHost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_url.is_delete
     *
     * @return the value of ss_url.is_delete
     *
     * @mbggenerated
     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_url.is_delete
     *
     * @param isDelete the value for ss_url.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ss_url.time
     *
     * @return the value of ss_url.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ss_url.time
     *
     * @param time the value for ss_url.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}